### ISSUE TITLE
Introduce `RegExp` object

### ISSUE THREAD

**Issue by radmen** [baethon/phln#3]
There's little confusion with those functions:
* `match()`
* `matchAll()`
* `replace()`
* `replaceAll()`
* `split()`
* `splitRegexp()`

Some of them require regexp, some of them require plain string. In fact all those functions could be simplified to only three:
* `match()`
* `replace()`
* `split()`

This can be done by introducting `RegExp` object which represents.. RegExp. It should be simply a ValueObject initialized in same fashion as in JS: `new RegExp($regex, $modifiers)`.

It should be able to handle *global* (`g`) modifier. For convenience it should be possible to create `RegExp` instance via `regexp()` function helper.

This should allow to:

* determine whether `match` or `replace` should perform action for all matches
* determine whether `split` should do it by regexp or plain text delimiter

Examples

```php
match('foo', 'foo bar foo'); // 'foo'
match(regexp('/foo/'), 'foo bar foo'); // 'foo'
match(regexp('/foo/', 'g'), 'foo bar foo'); // ['foo', 'foo']

replace('foo', 'foo bar foo'); // ' bar foo'
replace(regexp('/foo/'), 'foo bar foo'); // ' bar foo'
replace(regexp('/foo/', 'g'), 'foo bar foo'); // ' bar '
```

## TODO
- [x] `RegExp` class foundation
- [x] automatic delimiter wrapping of pattern (e.g `new RegExp('^foo') -> /^foo/`)
- [x] add `regexp()` function helper
- [x] add support for `RegExp` in `match()`
- [x] add support for `RegExp` in `replace()`
